import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'
import { Lightbulb, Eye, Copy, Check, ArrowLeft, Loader2 } from 'lucide-react'

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '../components/ui/Card'
import { Button } from '../components/ui/Button'
import { Progress } from '../components/ui/Progress'
import { Badge } from '../components/ui/Badge'
import { Skeleton } from '../components/ui/Skeleton'
import {
  Accordion, AccordionItem, AccordionTrigger, AccordionContent,
} from '../components/ui/Accordion'
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogTrigger,
} from '../components/ui/Dialog'
import { toast } from '../components/ui/use-toast'

import { getHints } from '../lib/api'
import { useQuiz, useUI } from '../lib/store'

const LEVEL_COPY = {
  vague:    { title: 'Hint 1 — Vague',    desc: 'A pointer to where in the passage to look.' },
  moderate: { title: 'Hint 2 — Moderate', desc: 'A specific sentence near the answer.' },
  specific: { title: 'Hint 3 — Specific', desc: 'The sentence containing the answer.' },
}

export default function Hints() {
  const navigate = useNavigate()
  const quiz = useQuiz()
  const bumpHints = useQuiz((s) => s.bumpHints)
  const hintsUsed = useQuiz((s) => s.hintsUsed)
  const pushLatency = useUI((s) => s.pushLatency)

  const [hints, setHints] = useState(null)
  const [busy, setBusy] = useState(true)
  const [revealed, setRevealed] = useState(false)
  const [copied, setCopied] = useState(false)
  const [open, setOpen] = useState(undefined)

  useEffect(() => {
    if (!quiz.question) {
      navigate('/', { replace: true })
      return
    }
    let mounted = true
    ;(async () => {
      setBusy(true)
      try {
        const r = await getHints(quiz.article, quiz.question)
        if (mounted) {
          setHints(r.hints)
          pushLatency(r.latency_ms)
        }
      } catch (e) {
        toast({ title: 'Hints failed', description: e.message, variant: 'destructive' })
      } finally {
        if (mounted) setBusy(false)
      }
    })()
    return () => { mounted = false }
  }, [quiz.question, quiz.article, navigate, pushLatency])

  const copyAnswer = async () => {
    const txt = quiz.answerText ?? quiz.options?.[quiz.answer] ?? quiz.answer
    if (!txt) return
    try {
      await navigator.clipboard.writeText(String(txt))
      setCopied(true)
      setTimeout(() => setCopied(false), 1400)
    } catch {
      toast({ title: 'Copy failed', variant: 'destructive' })
    }
  }

  const progressPct = (hintsUsed / 3) * 100

  if (!quiz.question) return null

  return (
    <div className="mx-auto w-full max-w-3xl px-4 md:px-6 py-8 md:py-12">
      <motion.div
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.35 }}
      >
        {/* Top bar */}
        <div className="mb-6 flex items-center gap-3">
          <Button variant="ghost" size="sm" onClick={() => navigate('/quiz')}>
            <ArrowLeft className="h-4 w-4" /> Back to quiz
          </Button>
          <div className="ml-auto flex items-center gap-3">
            <span className="text-xs text-muted-foreground">Hints used</span>
            <Badge variant="default" className="font-mono">
              {hintsUsed} / 3
            </Badge>
          </div>
        </div>

        <Card className="mb-6">
          <CardHeader>
            <div className="flex items-center gap-2">
              <Lightbulb className="h-4 w-4 text-accent" />
              <CardTitle>Need a nudge?</CardTitle>
            </div>
            <CardDescription className="leading-relaxed">
              Three graduated hints, generated by ranking sentences in the passage by their TF-IDF
              cosine similarity to the question. Open them in order — vague first.
            </CardDescription>
            <div className="pt-3">
              <Progress value={progressPct} />
            </div>
          </CardHeader>

          <CardContent>
            {busy ? (
              <div className="space-y-3">
                {[0, 1, 2].map((i) => (
                  <Skeleton key={i} className="h-14 w-full rounded-xl" />
                ))}
              </div>
            ) : (
              <Accordion
                type="single"
                collapsible
                value={open}
                onValueChange={(v) => {
                  setOpen(v)
                  if (v) bumpHints()
                }}
              >
                {(hints ?? []).map((h, i) => (
                  <AccordionItem key={h.level} value={`item-${i}`}>
                    <AccordionTrigger>
                      <div className="flex items-center gap-3">
                        <span className="grid h-7 w-7 place-items-center rounded-full bg-primary-soft text-primary text-xs font-semibold">
                          {i + 1}
                        </span>
                        <div>
                          <div className="text-sm font-semibold">{LEVEL_COPY[h.level]?.title ?? h.level}</div>
                          <div className="text-[12px] font-normal text-muted-foreground">
                            {LEVEL_COPY[h.level]?.desc}
                          </div>
                        </div>
                      </div>
                    </AccordionTrigger>
                    <AccordionContent>
                      <p className="text-foreground">{h.text}</p>
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            )}
          </CardContent>
        </Card>

        {/* Reveal answer */}
        <div className="flex flex-wrap items-center gap-3">
          <Dialog open={revealed} onOpenChange={setRevealed}>
            <DialogTrigger asChild>
              <Button variant="accent">
                <Eye className="h-4 w-4" /> Reveal Answer
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Correct answer</DialogTitle>
                <DialogDescription>From the gold key for this question.</DialogDescription>
              </DialogHeader>
              <div className="rounded-lg border border-border bg-muted/40 px-4 py-3">
                <div className="text-xs text-muted-foreground">Option</div>
                <div className="mt-0.5 text-2xl font-bold text-primary">
                  {quiz.answer ?? '—'}
                </div>
                <div className="mt-3 text-sm text-foreground/90 leading-relaxed">
                  {quiz.answerText ?? quiz.options?.[quiz.answer] ?? '—'}
                </div>
              </div>
              <div className="flex justify-end gap-2">
                <Button variant="outline" onClick={copyAnswer}>
                  {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                  {copied ? 'Copied' : 'Copy'}
                </Button>
              </div>
            </DialogContent>
          </Dialog>

          {busy && <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" />}
        </div>
      </motion.div>
    </div>
  )
}
